name: CD-Frontend

on:
  workflow_run:
    workflows:
      - CI-Frontend
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    name: Deploy Frontend
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted

    steps:

      - name: Checkout Infra
        uses: actions/checkout@v4
        with:
          repository: anakbaik-code/devops-infra
          path: infra

      - name: Deploy Frontend
        run: |
          docker compose \
          -f infra/docker-compose.yaml \
          pull frontend

          docker compose \
          -f infra/docker-compose.yaml \
          up -d frontend